plugins { id 'java' }

repositories {
    mavenLocal()
    maven { url = 'https://repo.runelite.net'; content { includeGroupByRegex('net\\.runelite.*') } }
    mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
    compileOnly "net.runelite:client:${runeLiteVersion}"
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation 'junit:junit:4.13.2'
    testImplementation "net.runelite:client:${runeLiteVersion}"
}

group = 'com.louie'
version = '1.0.0'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(11)
}

// Developer run task — launches RuneLite in dev mode with this plugin loaded
tasks.register('run', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'net.runelite.client.RuneLite'
    mainClass = 'com.louie.skillcolours.SkillColoursPluginLauncher'
    jvmArgs '-ea'
    args '--developer-mode', '--debug'
}
